# Generated by Django 4.1.3 on 2022-11-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_imgs')),
                ('discount_deal', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
