# Generated by Django 4.1.3 on 2022-11-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
