# Generated by Django 4.1.3 on 2022-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picking_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
