# Generated by Django 4.1.3 on 2022-11-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_picking_cost_product_packing_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
