# Generated by Django 4.1.3 on 2022-11-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
