# Generated by Django 4.1.3 on 2022-11-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_packing_cost_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
